### ISSUE TITLE
"error": "Invalid route plan with metadata"

### ISSUE THREAD

**Issue by mczarnecki-mtt** [jup-ag/jupiter-swap-api#39]
I am trying to run the jupiter-swap-api binary with the `--allow-circular-arbitrage` option and swap e.g SOL for SOL.
All the time, I am receiving the quote like this:
{
        "inputMint": "So11111111111111111111111111111111111111112",
        "inAmount": "10000000",
        "outputMint": "So11111111111111111111111111111111111111112",
        "outAmount": "10000000",
        "otherAmountThreshold": "5000000",
        "swapMode": "ExactIn",
        "slippageBps": 5000,
        "platformFee": null,
        "priceImpactPct": "0",
        "routePlan": [],
        "contextSlot": 281723668,
        "timeTaken": 0.030974171
    } 
    
When I input that quote as the "quoteResponse" field in POST /swap-instructions endpoint, I receive this error: `"error": "Invalid route plan with metadata"`. How can I resolve it?

**Comment by mexcro** [comment]
how you fix this?

**Comment by machoven** [comment]
circular arbitrage is enabled only swap endpoint.
so you set route plan manually

**Comment by CypherFury** [comment]
> circular arbitrage is enabled only swap endpoint. so you set route plan manually

Result with -allow-circular-arbitrage at the /quote endpoint with WSOL in input and in output : 

![image](https://github.com/user-attachments/assets/74559150-4ff5-43ae-ae40-4fda2637fa74)

Result without -allow-circular-arbitrage at the /quote endpoint with WSOL in input and in output : 

![image](https://github.com/user-attachments/assets/d953bc9d-e81c-4e0f-9019-76ba1a239c37)

So you're sure, "circular arbitrage is enabled only swap endpoint"? ahem.

Especially since the /swap endpoint simply builds a transaction based on the routes provided (by the /quote endpoint), so I don't see any connection whatsoever with circular arbitrage and transaction construction.

I don't mean to be rude, but are you sure you know what you're talking about? And if so, could you please explain a bit more please? :)

**Comment by shirotech** [comment]
+1 same error

**Comment by SeverusHuang-HLF** [comment]
hi, how you fix this?
